### ISSUE TITLE
What's the difference between procdump and gcore?

### ISSUE THREAD

**Issue by CaledoniaProject** [Microsoft/ProcDump-for-Linux#13]
Apart from conditional core dump, e.g monitoring the CPU usage of target process

What's the difference between this and the traditional `gcore` tool?

**Comment by MarioHewardt** [comment]
gcore is an on demand dump generation tool which works well in the low hanging fruit scenarios where issues are fully reproducible. In production however, that is rarely the case and you need a tool that can actively monitor and trigger dumps. We have a future work item to remove the dependency on gcore to allow more flexibility in the types of dumps we create.

**Comment by CaledoniaProject** [comment]
Thanks!
