### ISSUE TITLE
Post-build check failures on openSUSE

### ISSUE THREAD

**Issue by Conan-Kudo** [Microsoft/ProcDump-for-Linux#22]
During the building of procdump packages for openSUSE, the package failed the post build checks due to the following errors:

```
[   20s] I: Program returns random data in a function
[   20s] E: procdump no-return-in-nonvoid-function src/CoreDumpWriter.c:283
[   20s] E: procdump no-return-in-nonvoid-function src/ProcDumpConfiguration.c:467
```

### System information (e.g., distro, kernel version, etc.)
openSUSE Leap 42.3, openSUSE Tumbleweed (20171211)

**Comment by josalem** [comment]
This looks like the output from some kind of static code analysis tool.  Which tool did you use?  I can try to repro and triage whatever issues it is catching.

**Comment by Conan-Kudo** [comment]
This is done by the [openSUSE post-build-checks](https://github.com/openSUSE/post-build-checks):

The test in question is: `02-check-gcc-output`

```
[   34s] ... running 02-check-gcc-output
[   34s] ... testing for serious compiler warnings
[   34s]     (using /usr/lib/build/checks-data/check_gcc_output)
[   34s]     (using //.build.log)
[   34s] 
[   34s] I: Program returns random data in a function
[   34s] E: procdump no-return-in-nonvoid-function src/CoreDumpWriter.c:283
[   34s] E: procdump no-return-in-nonvoid-function src/ProcDumpConfiguration.c:467
```

The check: https://github.com/openSUSE/post-build-checks/blob/master/checks/02-check-gcc-output

The check data: https://github.com/openSUSE/post-build-checks/blob/master/checks-data/check_gcc_output
