### ISSUE TITLE
There is no install source for CentOS 7

### ISSUE THREAD

**Issue by xiexin36** [Microsoft/ProcDump-for-Linux#32]
### Expected behavior
Provide a install source for CentOS 7, I also tried to clone the source code and make it, the make process is OK, and I got the procdump file in the "bin" folder, but when I run the procdump, there is no file to create, I only got these on the console window.

root@bogon:/home/code/procdump/ProcDump-for-Linux/bin> ./procdump -p 5063 -n 3 -s 3 -C 80                                                                           18-08-21 11:40

ProcDump v1.0.1 - Sysinternals process dump utility
Copyright (C) 2017 Microsoft Corporation. All rights reserved. Licensed under the MIT license.
Mark Russinovich, Mario Hewardt, John Salem, Javid Habibi
Monitors a process and writes a dump file when the process exceeds the
specified criteria.

Process:		cat (5063)
CPU Threshold:		>=80
Commit Threshold:	n/a
Threshold Seconds:	3
Number of Dumps:	3

Press Ctrl-C to end monitoring without terminating the process.

[11:40:29 - INFO]: CPU:	97%
[11:40:33 - INFO]: CPU:	97%
[11:40:37 - INFO]: CPU:	97%
[09:53:42 - INFO]: Timed:

### Steps to reproduce the behavior
1. 
2.
3.

**Comment by xiexin36** [comment]
Any one can help me?

**Comment by jahabibi** [comment]
@xiexin36 I suspect that you may not have installed all the dependencies for Procdump. As per our [documentation](https://github.com/Microsoft/ProcDump-for-Linux#requirements) we depend on `gdb` for Procdump to work appropriately.

Can you provide the output of `yum list installed | grep gdb` on your system?

**Comment by xiexin36** [comment]
@jahabibi Thank you for your reply, Here is my output
[root@bd0 ~]# yum list installed | grep gdb
Repodata is over 2 weeks old. Install yum-cron? Or run: yum makecache fast
gdbm.x86_64                           1.10-8.el7                      @anaconda 
gdbm-devel.x86_64                     1.10-8.el7                      @base   

and I will try to install gdb

**Comment by xiexin36** [comment]
@jahabibi After install gdb with " yum install gdb", everything work fine. Thank you.

**Comment by jahabibi** [comment]
Not a problem! Glad to hear we were able to resolve this.
