### ISSUE TITLE
How to reduce the dump file size ?

### ISSUE THREAD

**Issue by xiexin36** [microsoft/ProcDump-for-Linux#33]
### Expected behavior
I use procdump to create a asp.net core process dump on centos 7, but the file size is too large, almost 25g. How to reduce the file size?
### Steps to reproduce the behavior
1. 
2.
3.

**Comment by MarioHewardt** [comment]
Currently, we use gcore to do the actual dump generation (hence have no control over how it actually does it). We have work in progress to create a custom core dumper that will allow us to better control the core dump generation process.

**Comment by xiexin36** [comment]
@MarioHewardt Any plan about this, when I can got the first preview version?

**Comment by xiexin36** [comment]
OK, Thanks

**Comment by jahabibi** [comment]
With the release of Procdump 1.1 we now have support for .NET Core 3.x+ core dump generation that results in manageable core dump sizes.
