### ISSUE TITLE
Unable to create dump

### ISSUE THREAD

**Issue by klesta490** [Microsoft/ProcDump-for-Linux#41]
### Expected behavior
Process dump is created

### Actual behavior
`root@8562a605f1fb# procdump -p 1`

ProcDump v1.0.1 - Sysinternals process dump utility
Copyright (C) 2017 Microsoft Corporation. All rights reserved. Licensed under the MIT license.
Mark Russinovich, Mario Hewardt, John Salem, Javid Habibi
Monitors a process and writes a dump file when the process exceeds the
specified criteria.

Process:     dotnet (1)
CPU Threshold:   n/a
Commit Threshold:  n/a
Threshold Seconds: 10
Number of Dumps: 1

Press Ctrl-C to end monitoring without terminating the process.

**[12:46:16 - INFO]: Timed:
[12:46:16 - ERROR]: An error occured while generating the core dump
[12:46:16 - ERROR]: GCORE - ptrace: Operation not permitted.
[12:46:16 - ERROR]: GCORE - You can't do that without a process to debug.
[12:46:16 - ERROR]: GCORE - The program is not being run.
[12:46:16 - ERROR]: GCORE - gcore: failed to create dotnet_time_2018-10-12_12:46:16.1**

### Steps to reproduce the behavior
1. build simple .NET Core app
2. dockerize it
3. bin/bash in docker image, install ProcDump-for-Linux according to guide [link](https://github.com/Microsoft/ProcDump-for-Linux)
4. `procdump -p 1`

### System information (e.g., distro, kernel version, etc.)
docker image microsoft/dotnet:2.1.4-runtime-stretch-slim

In container I am logged in as root user.

**Comment by rupran** [comment]
Being `root` alone is not sufficient, did you check that the container has the `SYS_PTRACE` capability? 

Either start the container using the command line parameter `--cap-add=SYS_PTRACE` or add it via a `docker-compose.yml`: 

```
cap_add:
    - SYS_PTRACE
```

**Comment by klesta490** [comment]
[Closed]
