### ISSUE TITLE
Create Debian Packages For Microsoft Apt Repo

### ISSUE THREAD

**Issue by sirredbeard** [microsoft/ProcDump-for-Linux#44]
This is a request for ProcDump to be built and included in the microsoft-debian-stretch-prod apt repository at [packages.microsoft.com](https://packages.microsoft.com/repos/microsoft-debian-stretch-prod/pool/main/).

The Xenial version works fine for now on Debian Stable but would prefer a build for Stable.

Thank you.

**Comment by jahabibi** [comment]
As of Procdump 1.1 we now have support for Debian and packages are available via our [install instructions](https://github.com/microsoft/ProcDump-for-Linux/blob/master/INSTALL.md).

**Comment by sirredbeard** [comment]
Thank you! Now we just need to get them in the Snap store too.
