### ISSUE TITLE
Support for Ubuntu 18.04

### ISSUE THREAD

**Issue by NatElkins** [microsoft/ProcDump-for-Linux#47]
Is Ubuntu 18.04 (Bionic) supported?  It's not mentioned in the readme and it's not in the bionic feed.  If not, what's the best way to start testing with it?

**Comment by MarioHewardt** [comment]
We've done some cursory testing on bionic...things seem to be working as expected.

**Comment by NatElkins** [comment]
Good to hear!  Might as well just put it out there then, at least as a preview (e.g. procdump-preview).

**Comment by jahabibi** [comment]
As of Procdump 1.1 we have release packages available via packages.microsoft.com. Check out our [install instructions](https://github.com/microsoft/ProcDump-for-Linux/blob/master/INSTALL.md) on how to download.
