### ISSUE TITLE
[Package format request] Please provide an AppImage for Linux

### ISSUE THREAD

**Issue by KurtPfeifle** [microsoft/ProcDump-for-Linux#6]
The only binary format of ProcDump-for-Linux currently is a *`.deb`* package.

It would be nice if you could provide an [AppImage](https://github.com/AppImage) as well. This project has a set of tools ([AppImageKit](https://github.com/AppImage/AppImageKit)) which can help to generate AppImages automatically from source code.

AppImages work on many different Linux distros out of the box. They are one single file (which internally is a squashfs-compressed file system, that, for running its payload app, uses a thin builtin helper runtime to temporarily mount the AppImage and execute the payload) only, which makes it super-easy for users to take advantage of it: No installation, no package manager, no root privileges required. Can run different versions of the same thing concurrently. Does not mess with system libraries either. Also easy to dispose of -- just delete the one file.

Your colleagues from the PowerShell department provide the [v6.0.0.0-Alpha9 and v6.0.0.0-rc as AppImages](https://github.com/PowerShell/PowerShell/releases) too. And it works rather nice:

[![asciicast](https://asciinema.org/a/145735.png)](https://asciinema.org/a/145735)

In AppImageKit there is a also tool, *`pkg2appimage`* which can convert the .deb to an AppImage. 

But maybe you want to integrate the AppImage (and .deb) creation into an automatic package generation using Travis CI?

**Comment by probonopd** [comment]
I have written an example `yml` recipe that can be used to convert the existing `.deb` into an AppImage:
https://github.com/AppImage/AppImages/blob/master/recipes/ProcDump.yml

Here is my test build:
https://bintray.com/probono/AppImages/ProcDump/1.0.glibc#files

Please note that this is for test purposes only. If there is interest from the ProcDump team, I'm happy to help making an official one, e.g., for continuous builds. In this case, we would not need to use Debian packages but could generate the AppImage directly during the build process.

**Comment by jahabibi** [comment]
Moving forward we intend to have a similar breadth of platform support as powershell for Linux. Thank you very much for bringing AppImage to our attention!

**Comment by KurtPfeifle** [comment]
Just so you know, I built myself an AppImage manually from the .deb package you provide. Its size is 162 KByte, and it works. 👍 

I also built an AppImage thru the recipe/.yml script probonopd quickly hacked together. This one creates an 11 MByte AppImage 👎 , but which also works. 👍  Somehow this automatically generated one has packed in a lot of Python stuff -- probably because somehow a gdb dependency made its way in (by human error in probonopd's recipe, or by a bug in the Debian dependency tree).

Just so you don't come to think that the AppImages are by default always so biiiiiig. No. This one must be fixed. :-)

**Comment by probonopd** [comment]
So, what are the __real__ dependencies of ProcDump?

**Comment by nikkitan** [comment]
> I have written an example yml recipe that can be used to convert the existing .deb into an AppImage:
> https://github.com/AppImage/AppImages/blob/master/recipes/ProcDump.yml
> To make an AppImage using it, run, on a deb-based system:
> wget https://raw.githubusercontent.com/AppImage/AppImages/master/pkg2appimage
> bash pkg2appimage ProcDump
> 
> Here is my test build:
> https://bintray.com/probono/AppImages/ProcDump/1.0.glibc#files
> Please note that this is for test purposes only. If there is interest from the ProcDump team, I'm happy to help making an official one, e.g., for continuous builds. In this case, we would not need to use Debian packages but could generate the AppImage directly during the build process.

@probonopd May I know in the Exec line in your ProcDump.yml, how were you planning to pass cmd line options to procdump? I'm asking also because in the spec of the .desktop file, I don't see it supports parameters besides filenames, URLs and directories.

**Comment by probonopd** [comment]
Possibly it already works? Invoke the AppImage with an argument and see if it works.

**Comment by nikkitan** [comment]
@probonopd I made an procdump.appimage by converting an existing .deb, which is very similar to what you did.  I did it with AppImageAssistant and an AppDir having the contents of an extracted .deb file(I saw this hello world way from the video by Simon Peter). But I ran into 2 issues: I still had to run the resultant appimage file with sudo, and procdump crashed because gcore couldn't open the core dump file.

**Comment by probonopd** [comment]
>  I made an procdump.appimage by converting an existing .deb
>  I did it with AppImageAssistant and an AppDir having the contents of an extracted .deb file

Why???

Please use:

```
wget https://raw.githubusercontent.com/AppImage/AppImages/master/pkg2appimage
bash pkg2appimage ProcDump
```

as written above. AppImageAssistant has been deprecated for many years and an AppImage made that way won't work properly.

> But I ran into 2 issues: I still had to run the resultant appimage file with sudo

I don't have this issue with my AppImage made with the commands above.

> and procdump crashed because gcore couldn't open the core dump file.

How can I test this? I don't know how what "gcore couldn't open the core dump file" means, can you give step-by-step instructions? Where do I get a "core dump file" from?

**Comment by nikkitan** [comment]
@probonopd The video is at the front page of AppImage's website and that's how I saw the deprecated method.  I'll try your method and keep here updated about what the team thinks about AppImage.

**Comment by probonopd** [comment]
Yes, that section of the video is utterly outdated by now. Thanks for reminding me that we need a new video. The `pkg2appimage` method is a quick (and somewhat dirty) way to automatically convert deb to AppImage. In case the ProcDump team wants to make "proper" AppImages, this can be done without going via a deb. In case the team is interested, I'm happy to help.

**Comment by nikkitan** [comment]
@probonopd I followed your method which uses your YML file. But I ran into the same 2 issues I had before: 1. 

> ./ProcDump-1.0.glibc2.17-x86_64.AppImage -p 1355

> ProcDump v1.0 - Sysinternals process dump utility
Copyright (C) 2017 Microsoft Corporation. All rights reserved. Licensed under ther MIT license.
Mark Russinovich, Mario Hewardt, John Salem, Javid Habibi
Monitors a process and writes a dump file when the process exceeds the
specified criteria.

> Process:                python3 (1355)
CPU Threshold:          n/a
Commit Threshold:       n/a
Threshold Seconds:      10
Number of Dumps:        1

> Press Ctrl-C to end monitoring without terminating the process.

> [06:43:09 - WARN]: Procdump not running with elevated credentails. If your uid does not match the uid of the target process procdump will not be able to capture memory dumps
> [06:43:09 - ERROR]: Target process is no longer alive


2. 

> sudo !!
sudo ./ProcDump-1.0.glibc2.17-x86_64.AppImage -p 1355

> ProcDump v1.0 - Sysinternals process dump utility
Copyright (C) 2017 Microsoft Corporation. All rights reserved. Licensed under ther MIT license.
Mark Russinovich, Mario Hewardt, John Salem, Javid Habibi
Monitors a process and writes a dump file when the process exceeds the
specified criteria.

> Process:                python3 (1355)
CPU Threshold:          n/a
Commit Threshold:       n/a
Threshold Seconds:      10
Number of Dumps:        1

> Press Ctrl-C to end monitoring without terminating the process.

> [06:44:50 - INFO]: Timed:
bash: /tmp/.mount_ProcDuYfWlLt/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by bash)
[06:44:51 - ERROR]: An error occured while generating the core dump
[06:44:51 - ERROR]: GCORE - warning: Could not load shared library symbols for linux-vdso.so.1.
[06:44:51 - ERROR]: GCORE - Do you need "set solib-search-path" or "set sysroot"?
[06:44:51 - ERROR]: GCORE - [New LWP 1433]
[06:44:51 - ERROR]: GCORE - [New LWP 1424]
[06:44:51 - ERROR]: GCORE - [Thread debugging using libthread_db enabled]
[06:44:51 - ERROR]: GCORE - Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[06:44:51 - ERROR]: GCORE - 0x00007f570752703f in __GI___select (nfds=0, readfds=0x0, writefds=0x0, exceptfds=0x0, timeout=0x7ffcc7d7a650) at ../sysdeps/unix/sysv/linux/select.c:41
[06:44:51 - ERROR]: GCORE - 41  ../sysdeps/unix/sysv/linux/select.c: No such file or directory.
[06:44:51 - ERROR]: GCORE - Failed to open 'python3_commit_2019-09-06_06:44:50.1355' for output.
[06:44:51 - ERROR]: GCORE - gcore: failed to create python3_commit_2019-09-06_06:44:50.1355

**Comment by probonopd** [comment]
Try without the -p argument. Then the AppImage runs fine.

I have no clue what this tool does or how it works... but I see that `-p` is causing some issue.

**Comment by probonopd** [comment]
Reeding

> Procdump not running with elevated credentails. If your uid does not match the uid of the target process procdump will not be able to capture memory dumps

it seems like the Procdump tool itself is what wants to be root. Nothing to do with AppImage.

Once you run with sudo, some portion of the code seems to get run which has issues in the current AppImage. Someone who knows what the application is doing there would have to have a look to see what is going wrong there.

**Comment by nikkitan** [comment]
@probobopd I brought up the sudo issue because I saw somewhere that one benefit of AppImage is that sudo is not needed. Now I realize this means for installation. But I thought AppImage doesn't require installation either? Anyway. Thanks for your clarification.

**Comment by probonopd** [comment]
Right, AppImages do not need to be installed. Just download, set the executable bit, and run. No installation needed, hence no root rights needed (like you would for installing a deb or rpm). What the application does is out of the scope of AppImage. AppImage is just a self-mounting filesystem that executes whatever the application author has put inside it. Much like a .dmg disk image file on the Mac.

**Comment by nikkitan** [comment]
Hi all, we appreciate the discussions, clarifications and voluntary works! After thorough and careful consideration, we see that after existing supports of Debian and RPM, ProcDump actually has reached similar breadth of platform as Powershell on Linux. So we currently are not considering adding support for AppImage.
