### ISSUE TITLE
There is no -w option in both ubuntu19.04 and ubuntu14.04.

### ISSUE THREAD

**Issue by Artis24106** [microsoft/ProcDump-for-Linux#66]
## OS
Ubuntu14.04, Ubuntu19.04

## Issue
I had tried to install ProcDump v1.0.1 via package manager and .deb. However, in both ways, there is no -w option.

**Comment by jahabibi** [comment]
Hey @Artis24106 thanks for pointing this out to us! We have resoleved this with the release of Procdump 1.1. We now support all current versions of Ubuntu. Try out the [new installation instructions](https://github.com/microsoft/ProcDump-for-Linux/blob/master/INSTALL.md) and let me know if you have any issues.
