### ISSUE TITLE
Unable to open crash dump with WinDbg

### ISSUE THREAD

**Issue by edavedian** [microsoft/ProcDump-for-Linux#73]
I used ProcDump for Linux to generate a crash dump of an ASP.NET core 2.2 application running on CentOS 7.7.  When I try to open that crash dump using WinDbg then I get "Win32 error 0n87" "The parameter is incorrect.

**Comment by MarioHewardt** [comment]
Opening Linux core dumps in WinDBG is not supported. You would have to either use the dotnet-* tools (https://github.com/dotnet/diagnostics/tree/master/documentation/tutorial) or LLDB on Linux to open the dump.
