### ISSUE TITLE
Coyright-Date not updated

### ISSUE THREAD

**Issue by theuserbl** [microsoft/ProcDump-for-Linux#85]
Only a minor thing.
But version 1.1.1 comes now out on April 2020 and if you start the program, it mentioned a "Copyright (C) 2019" :slightly_smiling_face: 

> ProcDump v1.1.1 - Sysinternals process dump utility
> Copyright (C) 2019 Microsoft Corporation. All rights reserved. Licensed under the MIT license.

**Comment by jahabibi** [comment]
Good catch! I have fix this and pushed updated packages.
